name: Nomad GHA Demo
run-name: ${{ github.actor }} is testing out Nomad actions
on: [push]
env:
  PRODUCT_VERSION: "1.5.6"

jobs:
  Deploy-Nomad-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup `nomad`
        uses: hashicorp/setup-nomad@v1.0.0-rc2
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}
      - name: Run `nomad version`
        run: "nomad version"
