name: Nomad GHA Demo
run-name: ${{ github.actor }} is testing out Nomad actions
on: [push]
env:
  PRODUCT_VERSION: "1.5.6"

jobs:
  Deploy-Nomad-Job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup `nomad`
        uses: lucasmelin/setup-nomad@v1
        with:
          version: ${{ env.PRODUCT_VERSION }}
      - name: Run `nomad version`
        run: "nomad version"
      - name: Use Local Action
        id: nomad-jwt-auth
        uses: "./"
        with:
          url: http://1fb0-50-35-64-228.ngrok-free.app
        continue-on-error: true
      - name: Print Token
        run: "echo token: ${{ steps.nomad-jwt-auth.outputs.nomad_token }}"
